name: Build
on: [ push ]

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Configure Git
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
      - name: Apply Patches
        run: |
          ./gradlew applyPatches --stacktrace
      - name: Build
        run: |
          ./gradlew build -x test createReobfPaperclipJar --stacktrace
      - name: Get MC Version
        run: echo "::set-output name=mcver::$(grep mcVersion gradle.properties | cut -d "=" -f2)"
        id: mcver
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%H:%M %m/%d/%Y')"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "AtelierMC Release ${{ steps.date.outputs.date }}"
          files: build/libs/ateliermc-paperclip-${{ steps.mcver.outputs.mcver }}-R0.1-SNAPSHOT-reobf.jar
