name: Build
on: [ push ]
jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Pull Gradle Cache
        uses: actions/cache@v2
        id: gradle-cache
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/gradle.properties') }}
      - name: Configure Git
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
      - name: Patch
        run: |
          ./gradlew applyPatches --stacktrace --no-daemon
      - name: Get MC Version
        run: echo "::set-output name=mcver::$(grep mcVersion gradle.properties | cut -d "=" -f2)"
        id: mcver
      - name: Build
        run: |
          ./gradlew build -x test createReobfPaperclipJar --stacktrace --no-daemon
      - name: Archive Paperclip
        uses: actions/upload-artifact@v2
        with:
          name: AtelierMC
          path: build/libs/ateliermc-paperclip-${{ steps.mcver.outputs.mcver }}-R0.1-SNAPSHOT-reobf.jar
